version: '2'
services:
  web:
    build: ./docker/web
    volumes:
      - .:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs/
    ports:
      - "80:80"
      - "443:443"
    hostname: webhost